### ISSUE TITLE
no-useless-spread: autofixer should remove trailing comma

### ISSUE THREAD

**Issue by ajafff** [fimbullinter/wotan#168]
Trailing commas inside the inner object or array literal should be removed in autofixes to avoid changing runtime semantics

```ts
[...[1,],];
// fixed to
[1,,]; // different meaning at runtime

({...{foo: 'foo',},});
// fixed to
({foo: 'foo',,}); // syntax error
```

There's another edge case with empty array literals:

```ts
[...[],]; // evaluates to empty array
// fixed to
[,]; // evaluates to a holey array
```

And yet another edge case with holey arrays (these should be ignored if no reassignment target):

```ts
[...[,],]; // evaluates to [undefined]
// fixed to
[,,]; // evaluates to [empty, empty]
// or
[,]; // evaluates to [empty]

// holey arrays in destructuring assignments should still result in an error:
[...[,a]] = [];
// fixed to
[, a] = []; // has the same semantics as above
```

/cc @aervin

**Comment by aervin** [comment]
First one seems fairly simple to fix, and the second is so specific it shouldn't be too hard either. 

The last one--the rule needs to check whether the array literal is filled with holes _only_ correct? And ignore the array literal if it's not part of a destructuring assignment?

Anyway, I agree these are pretty serious and will open a PR soon.

**Comment by ajafff** [comment]
> The last one--the rule needs to check whether the array literal is filled with holes *only* correct? 

the rule needs to check if the array literal has any amount of holes (`OmittedExpression`).

> And ignore the array literal if it's not part of a destructuring assignment?

correct, you can use `isReassignmentTarget` for that.
