### ISSUE TITLE
no-useless-spread: fixing object literal may break the code

### ISSUE THREAD

**Issue by ajafff** [fimbullinter/wotan#186]
Found while implementing #185

```ts
const named = 'bar';
let myObj = {
  foo: 1,
  bar: 1,
  ...{foo: 2, [named]: 2},
};

// fixed to
let myObj = {
  foo: 1,
  bar: 1,
  foo: 2, // duplicate key 'foo'
  [named]: 2, // duplicate key 'bar'
}
```

To reliably avoid this bug, the rule would need type information.
Also note that you would need to check on all parent objects, because multiple rule failures are fixed at once:

```ts
let myObj = {
  foo: 1,
  ...{...{foo: 2}, bar: 1},
};

// is currently fixed to:
let myObj = {
  foo: 1,
  foo: 2,
  bar: 1,
}
```

TBD: is it worth the effort to fix the autofixer or should we just remove the fixer for object literals entirely?

**Comment by aervin** [comment]
I know it's a contrived example, but I feel that anything like this
```ts
let myObj = {
  foo: 1,
  bar: 1,
  ...{foo: 2},
};
```
probably deserves to be looked at rather than auto-fixed, as it's likely the resulting object is not what the developer intends.

**Comment by ajafff** [comment]
I agree that this is better fixed by a human.
I opened #187 to remove the autofixer for object spread.
