### ISSUE TITLE
Discussion: rename fix baselines

### ISSUE THREAD

**Issue by ajafff** [fimbullinter/wotan#205]
@aervin in https://github.com/fimbullinter/wotan/pull/201#issuecomment-382855749

> @ajafff I've run into this a great deal, where I'm accidentally editing the wrong test.ts file (the baseline test file) because the test file and the baseline test files are named the same thing (and VSCode, in the tabs, abbreviates the name in a not-so-helpful manner). Any solution you can think of?

When I first introduced the baseline testing, I named the fixed files `test.ts.fix`. By default these have no syntax highlighting and type checking.

There are two options I can think of:
* use `test.ts.fix` and associate `*.fix` with TypeScript in `.vscode/settings.json`
  * has syntax highlighting and type checking (at least per file)
  * type checking doesn't work for relative imports
  * doesn't work out of the box in other IDEs
* use `test.fix.ts`
  * works in all editors
  * type checking works*
  * the name is probably not as clear as the one with the suffix

The type checking part is probably not as important as syntax highlighting (and noticing syntax errors). 
_*_ Also type checking is already broken because `tsconfig.json` is not copied to the baseline folder.

**Comment by ajafff** [comment]
You mean the squiggles and error message of failures that are not fixed? They interfere with the actual fixed content.
That is indeed a problem I don't know how to easily fix.

One could write a custom language extension for VSCode to strip these lines before passing them to TypeScript for syntax highlighting. But is it really worth the effort?

**Comment by aervin** [comment]
No, doesn't seem like its worth it. I'm just observing that the lint highlighting distracts from the syntax highlighting (which is most important in the baseline test files IMO).

**Comment by ajafff** [comment]
I went ahead and removed the error markup from the fix baselines in #214 

Now I'd like to tackle the naming issue. I think the easiest fix is renaming fix baselines to `*.fix` and associate that extension with the typescript extension for syntax highlighting. At least that's consistent with the `*.lint` baselines.

**Comment by aervin** [comment]
Thanks for taking the time to do that @ajafff . And I agree about the `*.fix` name change 👍
