### ISSUE TITLE
Implement Builder for Angular devkit

### ISSUE THREAD

**Issue by ajafff** [fimbullinter/wotan#255]
That enables using Wotan directly from the Angular CLI.

The implementation of the TslintBuilder for reference: 
https://github.com/angular/devkit/blob/8241f875bf5e0c8058b13f20db6a0f299d47ff53/packages/angular_devkit/build_angular/src/tslint/index.ts

**Comment by aervin** [comment]
@ajafff Want to express my support for this idea. Would be a big help :+1:

**Comment by CSchulz** [comment]
I have just started the work on it.

**Comment by ajafff** [comment]
@CSchulz that's great.

Make sure to also load the config *defaults* from `.fimbullinter.yaml` (https://github.com/fimbullinter/wotan/blob/master/packages/wotan/src/cli.ts#L23) and load all plugin modules for the DI container (https://github.com/fimbullinter/wotan/blob/master/packages/wotan/src/commands/index.ts#L20)

**Comment by ajafff** [comment]
@CSchulz is there any blocking issue or anything I can do to help you?

**Comment by ajafff** [comment]
Done: https://github.com/fimbullinter/circular/releases/tag/v0.0.1
