### ISSUE TITLE
TS3 peer-dependency

### ISSUE THREAD

**Issue by zerkms** [fimbullinter/wotan#355]
This issue is to track TS v3 (which was released today) compatibility

**Comment by ajafff** [comment]
What exactly do you have in mind?
The peerDependency already allows typescript@3.0.1.
Tests pass with latest typescript@3.0.1-insiders
I just changed CI to test with stable typescript@3.0.1

**Comment by zerkms** [comment]
I probably am looking at the wrong place then

https://github.com/fimbullinter/wotan/blob/master/package.json

```
  "peerDependencies": {
    "typescript": ">= 2.7.1 || >= 3.0.0-dev || >= 3.0.0-insiders || 3.0.0-rc || >= 3.1.0-dev"
  }
```

```
npm WARN @fimbul/bifrost@0.11.0 requires a peer of typescript@>= 2.7.1 || >= 3.0.0-dev || >= 3.0.0-insiders || 3.0.0-rc || >= 3.1.0-dev but none is installed. You must install peer dependencies yourself.
npm WARN @fimbul/ymir@0.11.0 requires a peer of typescript@>= 2.7.1 || >= 3.0.0-dev || >= 3.0.0-insiders || 3.0.0-rc || >= 3.1.0-dev but none is installed. You must install peer dependencies yourself.
```

**Comment by ajafff** [comment]
`>= 2.7.1` includes `3.0.1`.

What version of typescript do you have installed? Can you share a link to a repo?

**Comment by zerkms** [comment]
Right, I bumped `typescript` dependency to `^3.0.0` but seems like transitive dependencies did not allow it to install. Sorry!
