### ISSUE TITLE
Support Visual Studio Code

### ISSUE THREAD

**Issue by Shinigami92** [fimbullinter/wotan#396]
I would like to switch from TSLint to wotan, but as far as I can see, there is currently no possibility with wotan (without valtyr) in VSCode to show me problems.

Do we need a new VSCode extension for wotan?

Without linting files in VSCode this is currently a deal-breaker

**Comment by ajafff** [comment]
Currently there is no integration with VSCode.
This requires a new VSCode extension. Code-wise it could be very similar to `vscode-tslint`.

Conceptually it has the same problem as TSLint when it comes to rules that require type information. Creating a Program, which is the prerequisite of type information, is very expensive. That's a problem when linting on every file change.
I'm in favour of always linting with type information. Ideally there's no need to create the Program from scratch on every change, but incrementally update it like it's already done by the CLI runner.

**Comment by AlCalzone** [comment]
@ajafff Your linter seems like a very powerful tool. As I've been annoyed with TSLint in the past I have been wanting to switch. But the missing VSCode plugin is a dealbreaker.

**Comment by ajafff** [comment]
I just merged the LanguageService plugin. For those willing to test it: In about 3 hours there will be a new nightly release that includes the plugin. The documentation is located here: https://github.com/fimbullinter/wotan/blob/master/packages/mithotyn/README.md

Note: to install the nightly release you need to execute

```sh
npm install --save-dev @fimbul/wotan@next @fimbul/mithotyn@next
# or
yarn add -D @fimbul/wotan@next @fimbul/mithotyn@next
```

Any kind of feedback is very much appreciated.

---

Now I'll try to fix the remaining limitations and implement a plugin for VS Code.

**Comment by ajafff** [comment]
Turns out this was pretty easy to implement. So there you have it: https://marketplace.visualstudio.com/items?itemName=fimbullinter.vscode-plugin
