### ISSUE TITLE
Add rule that mimics --noImplicitAny compiler option

### ISSUE THREAD

**Issue by ajafff** [fimbullinter/wotan#432]
As discussed in https://github.com/Microsoft/TypeScript/issues/8855 there's a big demand to enable `--noImplicitAny` on a per-file basis. As this will not be supported by the compiler, this proposes duplicating that behavior as a lint rule.

IMO this rule should not be part of the recommended preset. If `--noImplicitAny` is already enabled the rule does nothing.

TODO:
* there are some differences in type inference depending on `--noImplicitAny` -> find out which and if we need to warn in these cases too.
* IIRC there was a PR to allow element access on a fresh object literal without index signature, but I can't find it right now.

Ref: https://github.com/palantir/tslint/issues/4215

**Comment by brainlessdeveloper** [comment]
Would love to work on this but I won't be able to get started until early next week. Could you point me to a PR that implements a similar rule?

**Comment by ajafff** [comment]
Is this still needed, now that https://github.com/Microsoft/TypeScript/pull/27693 added `noImplicitAny` errors as suggestions?
