### ISSUE TITLE
 Question: Will wotan support prettier?

### ISSUE THREAD

**Issue by xiaoxiangmoe** [fimbullinter/wotan#470]

**Comment by ajafff** [comment]
What do you mean by "support prettier"?

First of all, this repo will not add any formatting related rules. That means core rules do not conflict with prettier's formatting.

If you are asking for a way to integrate prettier into the linting process, you can use the existing https://www.npmjs.com/package/tslint-plugin-prettier and use [the Heimdall plugin](https://github.com/fimbullinter/wotan/blob/master/packages/heimdall/README.md) to use it within wotan. Be careful with that as there's a potential to destroy your code while autofixing.

On a related note: I also use prettier at work ... and it annoys the heck out of me.
