### ISSUE TITLE
**.vue.ts' is not a module.

### ISSUE THREAD

**Issue by rumanbsl** [fimbullinter/wotan#524]
I am trying to import .vue file in .ts. But the error is popping up on wotan
![image](https://user-images.githubusercontent.com/13895272/51032490-edcf8500-15a8-11e9-8d27-e187d3988b73.png)

**Comment by ajafff** [comment]
can you provide more details about your setup? How do you execute `wotan`, what configuration do you use, which rule is this error coming from?

**Comment by rumanbsl** [comment]
![image](https://user-images.githubusercontent.com/13895272/51034429-6d605280-15af-11e9-9831-7be7a287bb6c.png)
It's coming from typecheck

here is my tsconfig.json structure
```
{
  "strict": true,
  "include": [
    "src/**/*.ts",
    "src/**/*.vue",
    "./.storybook/**/*",
    "./webpack/**/*",
    "./gulpfile.babel.js"
  ],
  "exclude": [
    "./src/**/*.json",
  ],
  "compilerOptions": {
    "types": [
      "webpack-env",
      "jest",
      "node"
    ],
    "target": "es5",
    "strict": true,
    "module": "esnext",
    "moduleResolution": "node",
    "baseUrl": "./",
    "paths": {
      "@/*": [
        "./src/*"
      ],
      "src/*": [
        "./src/*"
      ],
      "storybook/*": [
        "./.storybook/*"
      ],
      "tests/*": [
        "./__tests__/*"
      ]
    },
    "strictNullChecks": true,
    "experimentalDecorators": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "allowSyntheticDefaultImports": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "esModuleInterop": true,
    "lib": [
      "dom",
      "es5",
      "es2015.promise",
      "es2017",
      "es6",
      "esnext"
    ],
    "resolveJsonModule": true
  }
}

```

I also have a vue type declaration file in the root of the project
```
// sfc.d.ts
declare module "*.vue" {
  import Vue from "vue";

  export default Vue;
}
```

**Comment by ajafff** [comment]
What's going on: Because `wotan` changes how the import is resolved, your wildcard declaration in `sfc.d.ts` no longer has an effect and TypeScript uses the extracted script from your SFC instead.

Does `index.vue` have a `<script>` element at all or it does it contain any `import` or `export`?

**Comment by ajafff** [comment]
Seems like this workaround fixed the error for you. I'm going to close this.

I opened #525 to find a correct solution that doesn't require a workaround like the one above.
