### ISSUE TITLE
Wotan reports "is not included in any of the projects" on Windows

### ISSUE THREAD

**Issue by teux** [fimbullinter/wotan#629]
When I lint one file (i.e. with precommit hook) on Window, wotan reports "is not included in any of the projects".
```text
'C:\/Users/IEUser/Documents/...' is not included in any of the projects: 'C:/Users/IEUser/Documents/...'
```
Pay attention to the root separator.

It is because of 3rd library normalize-glob which has error with file separator https://github.com/ajafff/normalize-glob/pull/10/files

**Comment by ajafff** [comment]
The fix is not available in v0.21.1.
Thank you for your patience, I lost myself in refactoring the release scripts ...

If you are still experiencing issues, please open a new issue.
