### ISSUE TITLE
async-function-assignability rule ignores overloading

### ISSUE THREAD

**Issue by avkoperskiy** [fimbullinter/wotan#655]
Next two snippets are differed in sequence of overloaded statements in `AnyFn` interface.

This snippet is OK
```typescript
interface AnyFn {
  (asyncFn?: () => PromiseLike<void>): void;
  (syncFn?: () => void): void;
}
const fn: AnyFn = (fn?: AnyFn) => {
  if (typeof fn === 'function') { fn() }
};
fn(async () => {});
```

Next snippet causes error
```typescript
interface AnyFn {
  (syncFn?: () => void): void;
  (asyncFn?: () => PromiseLike<void>): void;
}
const fn: AnyFn = (fn?: AnyFn) => {
  if (typeof fn === 'function') { fn() }
};
fn(async () => {});
   ^^^^^  "A 'Promise'-returning function should not be assigned to a 'void'-returning function type.wotan(async-function-assignability)"
```

**Comment by ajafff** [comment]
This is actually working as intended. The order of overload signatures matters in TypeScript. The first matching signature wins. Therefore the widest signature should be last.
The signature that takes a `void`-returning function is wider than the one with the `Promise`-returning function. So the first overload in your second example is kind of a catch-all and the second overload is never hit.

You can verify that by hovering over `fn(`. That will show the overload that TypeScript chooses (assuming you use some Monaco-like editor like VSCode or TypeScript Playground).

**Comment by avkoperskiy** [comment]
@ajafff 
Thank you for explanation!

My example is like prototype. In fact, the problem occurred with the @types/mocha.
They describe HookFunction overloads like this:
```typescript
interface HookFunction {
        (fn: Func): void;
        (fn: AsyncFunc): void;
...
```
See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mocha/index.d.ts#L336

Does your explanation mean that there is error in overload sequence?

![image](https://user-images.githubusercontent.com/51915532/66380524-5163d300-e9c0-11e9-9f27-18cf20616675.png)

**Comment by ajafff** [comment]
> Does your explanation mean that there is error in overload sequence?

Yep. The overloads need to be swapped.
I contributed a similar change for `@types/jasmine` and needed to place the async version before the sync one.
