### ISSUE TITLE
Can't find file vue.ts with tslint-microsoft-contrib

### ISSUE THREAD

**Issue by akoidan** [fimbullinter/wotan#661]
**tslint.json**:
```json
{
  "extends": ["./node_modules/tslint-microsoft-contrib/tslint.json"],
  "rulesDirectory": ["node_modules/tslint-microsoft-contrib"]
}
```
**Running**:
```bash
git clone https://github.com/akoidan/wotan-tslint-microsoft-contrib
cd wotan-tslint-microsoft-contrib
yarn install
wotan 'src/*.vue' -f verbose
```
**Produces**:
```
Error: ENOENT: no such file or directory, open '/tmp/lol/src/App.vue.ts'
    at Object.openSync (fs.js:451:3)
    at detectEncoding (/tmp/lol/node_modules/tslint/lib/rules/encodingRule.js:67:17)
    at walk (/tmp/lol/node_modules/tslint/lib/rules/encodingRule.js:49:20)
    at Rule.AbstractRule.applyWithFunction (/tmp/lol/node_modules/tslint/lib/language/rule/abstractRule.js:39:9)
    at Rule.apply (/tmp/lol/node_modules/tslint/lib/rules/encodingRule.js:33:21)
    at R.apply (/tmp/lol/node_modules/@fimbul/bifrost/src/index.js:30:40)
    at Linter.applyRules (/tmp/lol/node_modules/@fimbul/wotan/src/linter.js:209:31)
    at Linter.getFindings (/tmp/lol/node_modules/@fimbul/wotan/src/linter.js:125:25)
    at Runner.lintFiles (/tmp/lol/node_modules/@fimbul/wotan/src/runner.js:159:43)
    at lintFiles.next (<anonymous>) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/tmp/lol/src/App.vue.ts'
```

**Comment by ajafff** [comment]
The linter needs to provide fake file names for the compiler to make module resolution work as expected. These fake file names then make their way to the rules. Therefore a rule should never try to read the linted file again (as it might not actually exist with that path).

I'd suggest disabling this rule. Even if it didn't crash, it would still be really slow for a questionable benefit.

**Comment by akoidan** [comment]
> The linter needs to provide fake file names for the compiler to make module resolution work as expected. These fake file names then make their way to the rules. Therefore a rule should never try to read the linted file again (as it might not actually exist with that path).
> 
> I'd suggest disabling this rule. Even if it didn't crash, it would still be really slow for a questionable benefit.

There're not alternatives to set of rules that[ tslint-microsoft-contrib](https://github.com/microsoft/tslint-microsoft-contrib) provides, I don't really like to disable them, I'd love to use them

**Comment by ajafff** [comment]
> I don't really like to disable them

You don't need to disable all of the rules, only the one that doesn't work in this setup. 

> Provide file content, so linters wouldn't read the file

The content is there, that's why all other rules (including custom rules) work as expected.

> find another way to trick typescript to read filename even if it's not ending with .ts

I didn't find a better solution, but I'm happy to accept suggestions or contributions for that.

**Comment by akoidan** [comment]
> The content is there, that's why all other rules (including custom rules) work as expected.

Ok so the issue could be forwarded to tslin-microsoft since it's unclear why they are accessing the file while already having its content
