### ISSUE TITLE
Add rules to report syntax or type errors

### ISSUE THREAD

**Issue by ajafff** [fimbullinter/wotan#68]
@robinknaapen suggested on Gitter that it's useful to see compile errors directly in the linter output.
When linting a project, it's possible to request diagnostics for the current file from the compiler.

This proposes adding a new rule to Wotan core that show these diagnostics.
This rule will be not be enabled in the recommended config, because of the performance penalty and because typically you run `tsc` anyway.

**Caveat:** Since external dependencies are always excluded from linting, you'll not see errors in declaration files (e.g. duplicate identifier). That's like you had `skipLibCheck` enabled in your compilerOptions. At least you can make sure *your* code is correct.

**Comment by ajafff** [comment]
The implementation is not complicated at all. It only has 12 lines in total.

However it takes **a lot** of time to execute. Currently this adds around 30% to the total time it takes for Wotan to lint itself. 3150ms -> 4000ms

I'll try to tweak this a little. PR should be ready this evening.

**Comment by ajafff** [comment]
This could be split into two different rules: one for syntax errors and one for semantic errors.

The former could be implemented without type information once https://github.com/Microsoft/TypeScript/issues/21940 is resolved.

**Comment by robinknaapen** [comment]
In my opinion you should split this into two rules. This will create the advantage of adaptability.

**Comment by ajafff** [comment]
Released in v0.1.0
