### ISSUE TITLE
TypeScript 4.0 compatibility

### ISSUE THREAD

**Issue by AlCalzone** [fimbullinter/wotan#706]
Since TS 4.0, I'm getting this error when running `wotan`:
https://github.com/microsoft/TypeScript/issues/40301

@ajafff are you still working on wotan or do I have to abandon it? :cry:

**Comment by ajafff** [comment]
@AlCalzone thank you for reporing this crash.

> are you still working on wotan or do I have to abandon it?

I'll just pretend that I was not away for around 1,5 years and continue maintaining this project. There's a lot of exciting stuff to catch up on.

This crash also prevents me from updating to TS4.0 in this repo. Therefore it's one of my top priorities going forward.

**Comment by ajafff** [comment]
The fix was actually pretty simple. It's not a bug in TypeScript, but rather an unintended behavior that used to work and I (mis)used it in a rule.

Give me a bit more time to polish things up and update some of the outdated dependencies. There should be a release in the next few days.

**Comment by ajafff** [comment]
After some struggle with the release process and infrastructure, it's finally here: `v0.22.0` is now available, which fixes this issue.
